name: glogemflow_icetemp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=2.4
  - pandas>=3.0
  - scipy>=1.17
  - matplotlib>=3.10
  - jupyter
  - jupyterlab
  - ipykernel
  - xarray
  - netcdf4         # xarray backend for ERA5 .nc files
  - scikit-learn>=1.9
  - pip
  - pip:
    - cmcrameri>=1.8
